name: Maven Tests

on:
  push:
    branches: [ "*" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: true               # your BaseTest uses this to run Chrome headless on CI
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Run TestNG suite
        run: mvn -B -q test

      - name: Upload TestNG report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-output
          path: test-output

      - name: Upload screenshots (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots
          if-no-files-found: ignore
