name: Maven Tests

on:
  push:
    branches: [ "*" ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      # Install Google Chrome on the runner
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Show Chrome version
        run: chrome --version

      # Run the small CI suite you created
      - name: Run TestNG suite (CI)
        run: mvn -B -q -Dsurefire.suiteXmlFiles=testng-ci.xml test

      # Always upload reports, even on failure
      - name: Upload TestNG report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-output
          path: test-output

      - name: Upload screenshots (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots
          if-no-files-found: ignore
